// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLNS.Models;

#nullable disable

namespace QLNS.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLNS.Models.ChamCong", b =>
                {
                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<DateOnly>("NgayChamCong")
                        .HasColumnType("date");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("SoGioLam")
                        .HasColumnType("float");

                    b.Property<double?>("SoGioOt")
                        .HasColumnType("float")
                        .HasColumnName("SoGioOT");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNv", "NgayChamCong")
                        .HasName("PK__ChamCong__B80B19CA7B96F6FC");

                    b.ToTable("ChamCong");
                });

            modelBuilder.Entity("QLNS.Models.ChucVu", b =>
                {
                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<int?>("MaPhongBan")
                        .HasColumnType("int");

                    b.Property<string>("TenChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNv")
                        .HasName("PK__ChucVu__2725D70AF822882B");

                    b.HasIndex("MaPhongBan");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("QLNS.Models.GiamSat", b =>
                {
                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<int?>("BiGiamSat")
                        .HasColumnType("int");

                    b.HasKey("MaNv")
                        .HasName("PK__GiamSat__2725D70AE2F261F1");

                    b.HasIndex("BiGiamSat");

                    b.ToTable("GiamSat");
                });

            modelBuilder.Entity("QLNS.Models.Luong", b =>
                {
                    b.Property<int>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuong"));

                    b.Property<double?>("HeSoOt")
                        .HasColumnType("float")
                        .HasColumnName("HeSoOT");

                    b.Property<decimal?>("LuongCoBan")
                        .HasColumnType("money");

                    b.Property<decimal?>("LuongThucNhan")
                        .HasColumnType("money");

                    b.Property<int?>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<double?>("SoGioLam")
                        .HasColumnType("float");

                    b.Property<double?>("SoGioOt")
                        .HasColumnType("float")
                        .HasColumnName("SoGioOT");

                    b.Property<int?>("Thang")
                        .HasColumnType("int");

                    b.Property<double?>("TongOt")
                        .HasColumnType("float")
                        .HasColumnName("TongOT");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaLuong")
                        .HasName("PK__Luong__6609A48DB49D09BB");

                    b.HasIndex("MaNv");

                    b.HasIndex("TrangThai");

                    b.ToTable("Luong");
                });

            modelBuilder.Entity("QLNS.Models.NhanLuong", b =>
                {
                    b.Property<int>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<int>("MaLuong")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayNhan")
                        .HasColumnType("date");

                    b.HasKey("MaNv", "MaLuong")
                        .HasName("PK__NhanLuon__E1454D42E270AC80");

                    b.HasIndex("MaLuong");

                    b.ToTable("NhanLuong");
                });

            modelBuilder.Entity("QLNS.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNv"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaPhongBan")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDT");

                    b.HasKey("MaNv")
                        .HasName("PK__NhanVien__2725D70AA0CDE1AA");

                    b.HasIndex("MaPhongBan");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QLNS.Models.PhongBan", b =>
                {
                    b.Property<int>("MaPhongBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhongBan"));

                    b.Property<int?>("MaTruongPhong")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongNv")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongNV");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPhongBan")
                        .HasName("PK__PhongBan__D0910CC899BA9BEF");

                    b.HasIndex("MaTruongPhong");

                    b.ToTable("PhongBan");
                });

            modelBuilder.Entity("QLNS.Models.TaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<int?>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TenDangNhap")
                        .HasName("PK__TaiKhoan__55F68FC17A841706");

                    b.HasIndex("MaNv");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QLNS.Models.ToDoList", b =>
                {
                    b.Property<int>("ToDoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ToDoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToDoId"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("HanHoanThanh")
                        .HasColumnType("date");

                    b.Property<int?>("MaNguoiGiao")
                        .HasColumnType("int");

                    b.Property<int?>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<DateOnly?>("NgayTao")
                        .HasColumnType("date");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("ToDoId")
                        .HasName("PK__ToDoList__21D08D200783ED6B");

                    b.HasIndex("MaNguoiGiao");

                    b.HasIndex("MaNv");

                    b.HasIndex("TrangThai");

                    b.ToTable("ToDoList");
                });

            modelBuilder.Entity("QLNS.Models.TrangThai", b =>
                {
                    b.Property<byte>("MaTrangThai")
                        .HasColumnType("tinyint");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTrangThai")
                        .HasName("PK__TrangTha__AADE4138662E3168");

                    b.ToTable("TrangThai");
                });

            modelBuilder.Entity("QLNS.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro")
                        .HasName("PK__VaiTro__C24C41CF30E7F714");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("QLNS.Models.ChamCong", b =>
                {
                    b.HasOne("QLNS.Models.NhanVien", "MaNvNavigation")
                        .WithMany("ChamCongs")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__ChamCong__MaNV__72C60C4A");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("QLNS.Models.ChucVu", b =>
                {
                    b.HasOne("QLNS.Models.NhanVien", "MaNvNavigation")
                        .WithOne("ChucVu")
                        .HasForeignKey("QLNS.Models.ChucVu", "MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__ChucVu__MaNV__6477ECF3");

                    b.HasOne("QLNS.Models.PhongBan", "MaPhongBanNavigation")
                        .WithMany("ChucVus")
                        .HasForeignKey("MaPhongBan")
                        .HasConstraintName("FK__ChucVu__MaPhongB__656C112C");

                    b.Navigation("MaNvNavigation");

                    b.Navigation("MaPhongBanNavigation");
                });

            modelBuilder.Entity("QLNS.Models.GiamSat", b =>
                {
                    b.HasOne("QLNS.Models.NhanVien", "BiGiamSatNavigation")
                        .WithMany("GiamSatBiGiamSatNavigations")
                        .HasForeignKey("BiGiamSat")
                        .HasConstraintName("FK__GiamSat__BiGiamS__7A672E12");

                    b.HasOne("QLNS.Models.NhanVien", "MaNvNavigation")
                        .WithOne("GiamSatMaNvNavigation")
                        .HasForeignKey("QLNS.Models.GiamSat", "MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__GiamSat__MaNV__797309D9");

                    b.Navigation("BiGiamSatNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("QLNS.Models.Luong", b =>
                {
                    b.HasOne("QLNS.Models.NhanVien", "MaNvNavigation")
                        .WithMany("Luongs")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__Luong__MaNV__6FE99F9F");

                    b.HasOne("QLNS.Models.TrangThai", "TrangThaiNavigation")
                        .WithMany("Luongs")
                        .HasForeignKey("TrangThai")
                        .HasConstraintName("FK_Luong_TrangThai");

                    b.Navigation("MaNvNavigation");

                    b.Navigation("TrangThaiNavigation");
                });

            modelBuilder.Entity("QLNS.Models.NhanLuong", b =>
                {
                    b.HasOne("QLNS.Models.Luong", "MaLuongNavigation")
                        .WithMany("NhanLuongs")
                        .HasForeignKey("MaLuong")
                        .IsRequired()
                        .HasConstraintName("FK__NhanLuong__MaLuo__76969D2E");

                    b.HasOne("QLNS.Models.NhanVien", "MaNvNavigation")
                        .WithMany("NhanLuongs")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__NhanLuong__MaNV__75A278F5");

                    b.Navigation("MaLuongNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("QLNS.Models.NhanVien", b =>
                {
                    b.HasOne("QLNS.Models.PhongBan", "MaPhongBanNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaPhongBan")
                        .HasConstraintName("FK__NhanVien__MaPhon__60A75C0F");

                    b.Navigation("MaPhongBanNavigation");
                });

            modelBuilder.Entity("QLNS.Models.PhongBan", b =>
                {
                    b.HasOne("QLNS.Models.NhanVien", "MaTruongPhongNavigation")
                        .WithMany("PhongBans")
                        .HasForeignKey("MaTruongPhong")
                        .HasConstraintName("FK_PhongBan_TruongPhong");

                    b.Navigation("MaTruongPhongNavigation");
                });

            modelBuilder.Entity("QLNS.Models.TaiKhoan", b =>
                {
                    b.HasOne("QLNS.Models.NhanVien", "MaNvNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__TaiKhoan__MaNV__68487DD7");

                    b.HasOne("QLNS.Models.VaiTro", "MaVaiTroNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaVaiTro")
                        .HasConstraintName("FK__TaiKhoan__MaVaiT__693CA210");

                    b.Navigation("MaNvNavigation");

                    b.Navigation("MaVaiTroNavigation");
                });

            modelBuilder.Entity("QLNS.Models.ToDoList", b =>
                {
                    b.HasOne("QLNS.Models.NhanVien", "MaNguoiGiaoNavigation")
                        .WithMany("ToDoListMaNguoiGiaoNavigations")
                        .HasForeignKey("MaNguoiGiao")
                        .HasConstraintName("FK__ToDoList__MaNguo__6D0D32F4");

                    b.HasOne("QLNS.Models.NhanVien", "MaNvNavigation")
                        .WithMany("ToDoListMaNvNavigations")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__ToDoList__MaNV__6C190EBB");

                    b.HasOne("QLNS.Models.TrangThai", "TrangThaiNavigation")
                        .WithMany("ToDoLists")
                        .HasForeignKey("TrangThai")
                        .HasConstraintName("FK_ToDoList_TrangThai");

                    b.Navigation("MaNguoiGiaoNavigation");

                    b.Navigation("MaNvNavigation");

                    b.Navigation("TrangThaiNavigation");
                });

            modelBuilder.Entity("QLNS.Models.Luong", b =>
                {
                    b.Navigation("NhanLuongs");
                });

            modelBuilder.Entity("QLNS.Models.NhanVien", b =>
                {
                    b.Navigation("ChamCongs");

                    b.Navigation("ChucVu");

                    b.Navigation("GiamSatBiGiamSatNavigations");

                    b.Navigation("GiamSatMaNvNavigation");

                    b.Navigation("Luongs");

                    b.Navigation("NhanLuongs");

                    b.Navigation("PhongBans");

                    b.Navigation("TaiKhoans");

                    b.Navigation("ToDoListMaNguoiGiaoNavigations");

                    b.Navigation("ToDoListMaNvNavigations");
                });

            modelBuilder.Entity("QLNS.Models.PhongBan", b =>
                {
                    b.Navigation("ChucVus");

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("QLNS.Models.TrangThai", b =>
                {
                    b.Navigation("Luongs");

                    b.Navigation("ToDoLists");
                });

            modelBuilder.Entity("QLNS.Models.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
